services:
  infra-db-postgres-15:
    image: postgres:15-alpine
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_READ_SEARCH
      - FOWNER
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-root-password
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d postgres -U postgres']
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - infra-vol-postgres-15:/var/lib/postgresql/data
    networks:
      infra-net-postgres:
        aliases:
          - infra-db-postgres-15
    secrets:
      - postgres-root-password
########
  infra-db-postgres-17:
    image: postgres:17-alpine
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_READ_SEARCH
      - FOWNER
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-root-password
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d postgres -U postgres']
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - infra-vol-postgres-17:/var/lib/postgresql/data
    networks:
      infra-net-postgres:
        aliases:
          - infra-db-postgres-17
    secrets:
      - postgres-root-password
########
  infra-db-postgres-15-sqlproxy:
    image: alpine/socat:latest
    ports:
      - "5432:5432"
    networks:
      - infra-net-postgres
      - infra-net-shared
    command: >
      tcp-listen:5432,fork,reuseaddr 
      tcp-connect:infra-db-postgres-15:5432
########
  infra-db-postgres-17-sqlproxy:
    image: alpine/socat:latest
    ports:
      - "5433:5432"
    networks:
      - infra-net-postgres
      - infra-net-shared
    command: >
      tcp-listen:5432,fork,reuseaddr 
      tcp-connect:infra-db-postgres-17:5432
########
volumes:
  infra-vol-postgres-15:
  infra-vol-postgres-17:

networks:
  infra-net-postgres:
    external: true
  infra-net-shared:
    external: true

secrets:
  postgres-root-password:
    environment: POSTGRES_ROOT_PASSWORD
