services:
  app-ghostfolio-frontend:
    image: docker.io/ghostfolio/ghostfolio:latest
    restart: unless-stopped
    init: true
    stop_grace_period: 1m
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    depends_on:
      app-ghostfolio-redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?connect_timeout=300
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      ACCESS_TOKEN_SALT: ${ACCESS_TOKEN_SALT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    labels:
      - "dockhand.order=-1"
      - "dockhand.url=[Ghostfolio](https://ghostfolio.int.richtech.uk)"
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3333/api/v1/health']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      default:
      infra-net-nginxproxy:
        aliases:
          - app-ghostfolio-frontend-proxytarget
      infra-net-postgres:
      infra-net-shared:
############
  app-ghostfolio-redis:
    image: docker.io/library/redis:alpine
    restart: unless-stopped
    user: '999:1000'
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test:
        ['CMD-SHELL', 'redis-cli --pass "$${REDIS_PASSWORD}" ping | grep PONG']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      default:
        aliases:
          - app-ghostfolio-redis
############
networks:
  infra-net-nginxproxy:
    external: true
  infra-net-postgres:
    external: true
  infra-net-shared:
    external: true
  default:
    internal: true
