services:
  app-nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      TZ: ${NGINX_PROXY_TZ}
      DB_MYSQL_HOST: ${DATABASE_HOST}
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${DATABASE_USER}
      DB_MYSQL_PASSWORD__FILE: /run/secrets/nginx_dbuser_password
      DB_MYSQL_NAME: ${DATABASE_NAME}
      #DISABLE_IPV6: 'true'
    secrets:
      - nginx_dbuser_password
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - infra-net-nginxproxy
      - infra-net-mariadb
      - infra-net-shared  ## Required for ingress/egress
    volumes:
      - infra-vol-nginxproxy-data:/data
      - infra-vol-nginxproxy-letsencrypt:/etc/letsencrypt

volumes:
  infra-vol-nginxproxy-data: null
  infra-vol-nginxproxy-letsencrypt: null

networks:
  infra-net-nginxproxy:  # Internet only network
    external: true
  infra-net-mariadb:     # Internal only network
    external: true
  infra-net-shared:      # Ingress/Egress network. Inter Container Connectivity is disabled
    external: true

secrets:
  nginx_dbuser_password:
    environment: DATABASE_PASSWORD

